# @ai-generated: true
# @ai-tool: Copilot
name: PR Governance (licenses & secrets)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  contents: read
  pull-requests: write
  issues: write
  security-events: write

jobs:
  governance:
    name: Reusable AI governance checks
    # NOTE for downstream projects:
    # After copying workflows locally, prefer referencing the local reusable workflow file.
    uses: ./.github/workflows/ai-governance.yml
    with:
      run_markdownlint: true
      run_scancode: true
      run_sbom: true
      run_gitleaks: false
      run_dependency_review: false
      run_codeql: false
      lint_command: 'npm run lint'
      test_command: 'npm run test:ci'
      require_ui_transparency: true
      require_dpia_for_user_facing: true
      require_eval_for_high_risk: false
      enable_post_merge_reminders: true
